spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat-application
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/c-chat
  servlet:
    multipart:
      max-file-size: 50MB

  application:
    file:
      uploads:
        media-output.path: ./uploads