services:
  postgres:
    container_name: postgres-sql-cac
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: chat-application
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - chat-application
    restart: unless-stopped

  keycloak:
    container_name: keycloak-cac
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - chat-application
    command:
      - "start-dev"

networks:
  chat-application:
    driver: bridge

volumes:
  postgres:
    driver: local
